// levels_data.dart
// Dữ liệu 25 cấp độ x 25 từ vựng B1 - tự động sinh, không sửa tay file này

class WordItem {
  final String word;
  final String meaning;
  const WordItem(this.word, this.meaning);
}

class LevelInfo {
  final int id;
  final String title;
  final List<WordItem> words;
  const LevelInfo(this.id, this.title, this.words);
}

final List<LevelInfo> allLevels = [
  LevelInfo(1, 'Daily Routines', [
    WordItem('wake up', 'thức dậy'),
    WordItem('get dressed', 'mặc quần áo'),
    WordItem('brush teeth', 'đánh răng'),
    WordItem('have breakfast', 'ăn sáng'),
    WordItem('commute', 'đi làm/đi học hàng ngày'),
    WordItem('leave home', 'rời khỏi nhà'),
    WordItem('arrive', 'đến nơi'),
    WordItem('take a shower', 'tắm vòi sen'),
    WordItem('go to bed', 'đi ngủ'),
    WordItem('fall asleep', 'chìm vào giấc ngủ'),
    WordItem('set an alarm', 'đặt báo thức'),
    WordItem('oversleep', 'ngủ quên'),
    WordItem('rush', 'vội vã'),
    WordItem('routine', 'thói quen hàng ngày'),
    WordItem('chores', 'việc nhà'),
    WordItem('tidy up', 'dọn dẹp'),
    WordItem('relax', 'thư giãn'),
    WordItem('nap', 'ngủ trưa ngắn'),
    WordItem('exhausted', 'kiệt sức'),
    WordItem('refreshed', 'sảng khoái'),
    WordItem('schedule', 'lịch trình'),
    WordItem('errand', 'việc vặt cần làm'),
    WordItem('habit', 'thói quen'),
    WordItem('punctual', 'đúng giờ'),
    WordItem('lazy', 'lười biếng'),
  ]),
  LevelInfo(2, 'Food & Cooking', [
    WordItem('ingredient', 'nguyên liệu'),
    WordItem('recipe', 'công thức nấu ăn'),
    WordItem('boil', 'luộc/đun sôi'),
    WordItem('fry', 'chiên'),
    WordItem('bake', 'nướng (bằng lò)'),
    WordItem('grill', 'nướng (trên vỉ)'),
    WordItem('chop', 'thái/băm'),
    WordItem('slice', 'cắt lát'),
    WordItem('stir', 'khuấy'),
    WordItem('taste', 'nếm thử'),
    WordItem('spicy', 'cay'),
    WordItem('sour', 'chua'),
    WordItem('bitter', 'đắng'),
    WordItem('delicious', 'ngon'),
    WordItem('leftover', 'đồ ăn thừa'),
    WordItem('appetite', 'cảm giác thèm ăn'),
    WordItem('diet', 'chế độ ăn uống'),
    WordItem('vegetarian', 'người ăn chay'),
    WordItem('portion', 'khẩu phần'),
    WordItem('seasoning', 'gia vị'),
    WordItem('meal', 'bữa ăn'),
    WordItem('snack', 'đồ ăn vặt'),
    WordItem('starve', 'đói lả'),
    WordItem('stuffed', 'no căng bụng'),
    WordItem('nutritious', 'bổ dưỡng'),
  ]),
  LevelInfo(3, 'Travel & Transport', [
    WordItem('journey', 'hành trình'),
    WordItem('destination', 'điểm đến'),
    WordItem('luggage', 'hành lý'),
    WordItem('board', 'lên (máy bay/tàu)'),
    WordItem('depart', 'khởi hành'),
    WordItem('arrival', 'sự đến nơi'),
    WordItem('delay', 'sự chậm trễ'),
    WordItem('passenger', 'hành khách'),
    WordItem('fare', 'giá vé'),
    WordItem('route', 'tuyến đường'),
    WordItem('accommodation', 'chỗ ở'),
    WordItem('reservation', 'sự đặt trước'),
    WordItem('itinerary', 'lịch trình chuyến đi'),
    WordItem('sightseeing', 'tham quan'),
    WordItem('souvenir', 'quà lưu niệm'),
    WordItem('crowded', 'đông đúc'),
    WordItem('abroad', 'ở nước ngoài'),
    WordItem('customs', 'hải quan'),
    WordItem('passport', 'hộ chiếu'),
    WordItem('transit', 'quá cảnh'),
    WordItem('commuter', 'người đi làm hàng ngày'),
    WordItem('explore', 'khám phá'),
    WordItem('wander', 'đi lang thang'),
    WordItem('backpack', 'ba lô'),
    WordItem('map out', 'lên kế hoạch (chi tiết)'),
  ]),
  LevelInfo(4, 'Family & Relationships', [
    WordItem('sibling', 'anh chị em ruột'),
    WordItem('relative', 'họ hàng'),
    WordItem('in-laws', 'gia đình bên vợ/chồng'),
    WordItem('raise (children)', 'nuôi dạy (con cái)'),
    WordItem('upbringing', 'sự nuôi dạy'),
    WordItem('resemble', 'giống với'),
    WordItem('get along', 'hòa hợp'),
    WordItem('argue', 'tranh cãi'),
    WordItem('apologize', 'xin lỗi'),
    WordItem('forgive', 'tha thứ'),
    WordItem('trust', 'tin tưởng'),
    WordItem('support', 'hỗ trợ'),
    WordItem('close-knit', 'gắn bó khăng khít'),
    WordItem('generation', 'thế hệ'),
    WordItem('ancestor', 'tổ tiên'),
    WordItem('engaged', 'đính hôn'),
    WordItem('divorce', 'ly hôn'),
    WordItem('single parent', 'cha/mẹ đơn thân'),
    WordItem('bond', 'mối liên kết'),
    WordItem('nurture', 'chăm sóc, nuôi dưỡng'),
    WordItem('dependent', 'người phụ thuộc'),
    WordItem('household', 'hộ gia đình'),
    WordItem('reunion', 'cuộc đoàn tụ'),
    WordItem('caring', 'biết quan tâm'),
    WordItem('strict', 'nghiêm khắc'),
  ]),
  LevelInfo(5, 'Work & Jobs', [
    WordItem('employer', 'chủ sử dụng lao động'),
    WordItem('employee', 'nhân viên'),
    WordItem('colleague', 'đồng nghiệp'),
    WordItem('promotion', 'sự thăng chức'),
    WordItem('resign', 'từ chức'),
    WordItem('apply for', 'nộp đơn xin (việc)'),
    WordItem('interview', 'phỏng vấn'),
    WordItem('salary', 'lương'),
    WordItem('overtime', 'làm thêm giờ'),
    WordItem('deadline', 'hạn chót'),
    WordItem('responsibility', 'trách nhiệm'),
    WordItem('qualification', 'bằng cấp/trình độ'),
    WordItem('experience', 'kinh nghiệm'),
    WordItem('unemployed', 'thất nghiệp'),
    WordItem('career', 'sự nghiệp'),
    WordItem('workload', 'khối lượng công việc'),
    WordItem('negotiate', 'đàm phán'),
    WordItem('multitask', 'làm nhiều việc cùng lúc'),
    WordItem('efficient', 'hiệu quả'),
    WordItem('meeting', 'cuộc họp'),
    WordItem('supervisor', 'người giám sát'),
    WordItem('intern', 'thực tập sinh'),
    WordItem('skill', 'kỹ năng'),
    WordItem('achievement', 'thành tựu'),
    WordItem('workplace', 'nơi làm việc'),
  ]),
  LevelInfo(6, 'Health & Body', [
    WordItem('symptom', 'triệu chứng'),
    WordItem('illness', 'bệnh tật'),
    WordItem('recover', 'hồi phục'),
    WordItem('prescription', 'đơn thuốc'),
    WordItem('appointment', 'cuộc hẹn (khám bệnh)'),
    WordItem('injury', 'chấn thương'),
    WordItem('treatment', 'sự điều trị'),
    WordItem('exercise', 'tập thể dục'),
    WordItem('diet', 'chế độ ăn'),
    WordItem('fatigue', 'sự mệt mỏi'),
    WordItem('headache', 'đau đầu'),
    WordItem('fever', 'sốt'),
    WordItem('allergy', 'dị ứng'),
    WordItem('nutrient', 'chất dinh dưỡng'),
    WordItem('posture', 'tư thế cơ thể'),
    WordItem('stress', 'căng thẳng'),
    WordItem('immune system', 'hệ miễn dịch'),
    WordItem('checkup', 'khám sức khỏe định kỳ'),
    WordItem('wound', 'vết thương'),
    WordItem('dose', 'liều lượng'),
    WordItem('pharmacy', 'hiệu thuốc'),
    WordItem('well-being', 'sự khỏe mạnh, an lành'),
    WordItem('breathe', 'hít thở'),
    WordItem('faint', 'ngất xỉu'),
    WordItem('pulse', 'nhịp mạch'),
  ]),
  LevelInfo(7, 'Weather & Seasons', [
    WordItem('humid', 'ẩm ướt'),
    WordItem('drizzle', 'mưa phùn'),
    WordItem('thunderstorm', 'dông bão'),
    WordItem('forecast', 'dự báo thời tiết'),
    WordItem('temperature', 'nhiệt độ'),
    WordItem('breeze', 'làn gió nhẹ'),
    WordItem('frost', 'sương giá'),
    WordItem('drought', 'hạn hán'),
    WordItem('flood', 'lũ lụt'),
    WordItem('shade', 'bóng râm'),
    WordItem('sunrise', 'bình minh'),
    WordItem('sunset', 'hoàng hôn'),
    WordItem('overcast', 'u ám (nhiều mây)'),
    WordItem('gale', 'gió mạnh'),
    WordItem('hail', 'mưa đá'),
    WordItem('mild', 'ôn hòa (thời tiết)'),
    WordItem('chilly', 'se lạnh'),
    WordItem('scorching', 'nóng như thiêu'),
    WordItem('blizzard', 'bão tuyết'),
    WordItem('puddle', 'vũng nước'),
    WordItem('visibility', 'tầm nhìn xa'),
    WordItem('climate', 'khí hậu'),
    WordItem('seasonal', 'theo mùa'),
    WordItem('thaw', 'tan (băng tuyết)'),
    WordItem('damp', 'ẩm ướt (nhẹ)'),
  ]),
  LevelInfo(8, 'Shopping & Money', [
    WordItem('receipt', 'hóa đơn'),
    WordItem('refund', 'hoàn tiền'),
    WordItem('discount', 'giảm giá'),
    WordItem('afford', 'có đủ khả năng chi trả'),
    WordItem('budget', 'ngân sách'),
    WordItem('bargain', 'món hời/mặc cả'),
    WordItem('customer', 'khách hàng'),
    WordItem('cashier', 'thu ngân'),
    WordItem('installment', 'trả góp'),
    WordItem('expense', 'chi phí'),
    WordItem('income', 'thu nhập'),
    WordItem('savings', 'tiền tiết kiệm'),
    WordItem('debt', 'nợ'),
    WordItem('loan', 'khoản vay'),
    WordItem('currency', 'tiền tệ'),
    WordItem('invoice', 'hóa đơn thanh toán'),
    WordItem('warranty', 'bảo hành'),
    WordItem('exchange', 'đổi (hàng/tiền)'),
    WordItem('overpriced', 'đắt quá mức'),
    WordItem('value for money', 'đáng đồng tiền'),
    WordItem('transaction', 'giao dịch'),
    WordItem('wholesale', 'bán buôn'),
    WordItem('retail', 'bán lẻ'),
    WordItem('subscription', 'đăng ký thuê bao'),
    WordItem('withdraw (money)', 'rút tiền'),
  ]),
  LevelInfo(9, 'House & Furniture', [
    WordItem('furniture', 'đồ nội thất'),
    WordItem('landlord', 'chủ nhà cho thuê'),
    WordItem('tenant', 'người thuê nhà'),
    WordItem('rent', 'tiền thuê nhà'),
    WordItem('lease', 'hợp đồng thuê'),
    WordItem('mortgage', 'khoản vay mua nhà'),
    WordItem('spacious', 'rộng rãi'),
    WordItem('cramped', 'chật chội'),
    WordItem('renovate', 'cải tạo, tu sửa'),
    WordItem('furnished', 'có sẵn nội thất'),
    WordItem('appliance', 'thiết bị gia dụng'),
    WordItem('basement', 'tầng hầm'),
    WordItem('attic', 'gác mái'),
    WordItem('balcony', 'ban công'),
    WordItem('neighbourhood', 'khu dân cư'),
    WordItem('utility bill', 'hóa đơn tiện ích'),
    WordItem('plumbing', 'hệ thống ống nước'),
    WordItem('maintenance', 'bảo trì'),
    WordItem('cosy', 'ấm cúng'),
    WordItem('move in', 'dọn vào ở'),
    WordItem('move out', 'dọn ra khỏi (nhà)'),
    WordItem('decorate', 'trang trí'),
    WordItem('household chores', 'việc nhà'),
    WordItem('clutter', 'sự bừa bộn'),
    WordItem('storage room', 'phòng chứa đồ'),
  ]),
  LevelInfo(10, 'Clothes & Fashion', [
    WordItem('outfit', 'bộ trang phục'),
    WordItem('trend', 'xu hướng'),
    WordItem('fabric', 'vải'),
    WordItem('fit (clothes)', 'vừa vặn'),
    WordItem('loose', 'rộng thùng thình'),
    WordItem('tight', 'chật'),
    WordItem('stylish', 'thời trang, sành điệu'),
    WordItem('casual', 'xuề xòa, thường ngày'),
    WordItem('formal', 'trang trọng'),
    WordItem('accessory', 'phụ kiện'),
    WordItem('wardrobe', 'tủ quần áo'),
    WordItem('try on', 'thử (quần áo)'),
    WordItem('brand', 'thương hiệu'),
    WordItem('size', 'kích cỡ'),
    WordItem('pattern', 'họa tiết'),
    WordItem('shabby', 'cũ kỹ, sờn rách'),
    WordItem('elegant', 'thanh lịch'),
    WordItem('second-hand', 'đồ đã qua sử dụng'),
    WordItem('laundry', 'đồ giặt'),
    WordItem('iron (clothes)', 'ủi (quần áo)'),
    WordItem('stain', 'vết bẩn'),
    WordItem('match (colors)', 'phối hợp (màu sắc)'),
    WordItem('fashionable', 'hợp thời trang'),
    WordItem('designer', 'nhà thiết kế'),
    WordItem('footwear', 'giày dép'),
  ]),
  LevelInfo(11, 'Free Time & Hobbies', [
    WordItem('leisure', 'thời gian rảnh'),
    WordItem('hobby', 'sở thích'),
    WordItem('collect', 'sưu tầm'),
    WordItem('enthusiast', 'người đam mê'),
    WordItem('relaxing', 'thư giãn'),
    WordItem('boredom', 'sự nhàm chán'),
    WordItem('entertainment', 'giải trí'),
    WordItem('gathering', 'buổi tụ họp'),
    WordItem('board game', 'trò chơi trên bàn'),
    WordItem('craft', 'thủ công'),
    WordItem('painting', 'hội họa'),
    WordItem('gardening', 'làm vườn'),
    WordItem('photography', 'nhiếp ảnh'),
    WordItem('knitting', 'đan len'),
    WordItem('puzzle', 'trò chơi xếp hình'),
    WordItem('recreational', 'có tính giải trí'),
    WordItem('pastime', 'thú tiêu khiển'),
    WordItem('volunteer', 'tình nguyện viên'),
    WordItem('membership', 'tư cách thành viên'),
    WordItem('participate', 'tham gia'),
    WordItem('skillful', 'khéo léo'),
    WordItem('chill out', 'thư giãn, xả hơi'),
    WordItem('unwind', 'xả stress'),
    WordItem('engaging', 'hấp dẫn, lôi cuốn'),
    WordItem('passionate', 'đam mê'),
  ]),
  LevelInfo(12, 'Sports', [
    WordItem('compete', 'thi đấu'),
    WordItem('opponent', 'đối thủ'),
    WordItem('referee', 'trọng tài'),
    WordItem('championship', 'giải vô địch'),
    WordItem('teammate', 'đồng đội'),
    WordItem('score a goal', 'ghi bàn'),
    WordItem('defeat', 'đánh bại'),
    WordItem('tournament', 'giải đấu'),
    WordItem('training', 'luyện tập'),
    WordItem('stamina', 'sức bền'),
    WordItem('injury', 'chấn thương'),
    WordItem('coach', 'huấn luyện viên'),
    WordItem('spectator', 'khán giả'),
    WordItem('stadium', 'sân vận động'),
    WordItem('draw (match)', 'trận hòa'),
    WordItem('qualify', 'đủ điều kiện (vào vòng trong)'),
    WordItem('warm up', 'khởi động'),
    WordItem('fitness', 'thể lực'),
    WordItem('athlete', 'vận động viên'),
    WordItem('record (sports)', 'kỷ lục'),
    WordItem('penalty', 'quả phạt đền'),
    WordItem('substitute', 'cầu thủ dự bị'),
    WordItem('victory', 'chiến thắng'),
    WordItem('underdog', 'đội yếu thế hơn'),
    WordItem('cheer', 'cổ vũ'),
  ]),
  LevelInfo(13, 'Nature & Environment', [
    WordItem('pollution', 'ô nhiễm'),
    WordItem('recycle', 'tái chế'),
    WordItem('wildlife', 'động vật hoang dã'),
    WordItem('ecosystem', 'hệ sinh thái'),
    WordItem('endangered', 'có nguy cơ tuyệt chủng'),
    WordItem('resource', 'tài nguyên'),
    WordItem('sustainable', 'bền vững'),
    WordItem('deforestation', 'phá rừng'),
    WordItem('emission', 'khí thải'),
    WordItem('conservation', 'sự bảo tồn'),
    WordItem('renewable', 'có thể tái tạo'),
    WordItem('landscape', 'cảnh quan'),
    WordItem('habitat', 'môi trường sống (của loài vật)'),
    WordItem('greenhouse effect', 'hiệu ứng nhà kính'),
    WordItem('global warming', 'sự nóng lên toàn cầu'),
    WordItem('preserve', 'bảo tồn, giữ gìn'),
    WordItem('waste', 'rác thải'),
    WordItem('organic', 'hữu cơ'),
    WordItem('solar energy', 'năng lượng mặt trời'),
    WordItem('biodiversity', 'đa dạng sinh học'),
    WordItem('erosion', 'sự xói mòn'),
    WordItem('contaminate', 'làm ô nhiễm'),
    WordItem('fossil fuel', 'nhiên liệu hóa thạch'),
    WordItem('drought', 'hạn hán'),
    WordItem('reforestation', 'trồng lại rừng'),
  ]),
  LevelInfo(14, 'Technology', [
    WordItem('device', 'thiết bị'),
    WordItem('upgrade', 'nâng cấp'),
    WordItem('software', 'phần mềm'),
    WordItem('hardware', 'phần cứng'),
    WordItem('battery life', 'thời lượng pin'),
    WordItem('charger', 'bộ sạc'),
    WordItem('wireless', 'không dây'),
    WordItem('download', 'tải xuống'),
    WordItem('upload', 'tải lên'),
    WordItem('password', 'mật khẩu'),
    WordItem('browser', 'trình duyệt'),
    WordItem('storage', 'bộ nhớ lưu trữ'),
    WordItem('crash (app)', 'bị treo/sập (ứng dụng)'),
    WordItem('update', 'cập nhật'),
    WordItem('backup', 'sao lưu'),
    WordItem('virus (computer)', 'vi-rút máy tính'),
    WordItem('network', 'mạng'),
    WordItem('connectivity', 'khả năng kết nối'),
    WordItem('innovative', 'mang tính sáng tạo/đổi mới'),
    WordItem('malfunction', 'trục trặc, hỏng hóc'),
    WordItem('subscription', 'đăng ký thuê bao'),
    WordItem('interface', 'giao diện'),
    WordItem('troubleshoot', 'khắc phục sự cố'),
    WordItem('gadget', 'thiết bị công nghệ nhỏ gọn'),
    WordItem('automation', 'tự động hóa'),
  ]),
  LevelInfo(15, 'Education & School', [
    WordItem('curriculum', 'chương trình học'),
    WordItem('assignment', 'bài tập được giao'),
    WordItem('lecture', 'bài giảng'),
    WordItem('graduate', 'tốt nghiệp'),
    WordItem('scholarship', 'học bổng'),
    WordItem('tuition', 'học phí'),
    WordItem('semester', 'học kỳ'),
    WordItem('classmate', 'bạn học cùng lớp'),
    WordItem('attendance', 'sự có mặt/điểm danh'),
    WordItem('revise', 'ôn tập'),
    WordItem('plagiarism', 'đạo văn'),
    WordItem('literacy', 'khả năng đọc viết'),
    WordItem('enroll', 'ghi danh, đăng ký học'),
    WordItem('major (subject)', 'chuyên ngành'),
    WordItem('dropout', 'người bỏ học'),
    WordItem('grade', 'điểm số'),
    WordItem('textbook', 'sách giáo khoa'),
    WordItem('supervisor (academic)', 'người hướng dẫn học tập'),
    WordItem('thesis', 'luận văn'),
    WordItem('distraction', 'sự sao nhãng'),
    WordItem('motivated', 'có động lực'),
    WordItem('comprehension', 'khả năng hiểu'),
    WordItem('academic', 'thuộc về học thuật'),
    WordItem('extracurricular', 'ngoại khóa'),
    WordItem('achievement', 'thành tích'),
  ]),
  LevelInfo(16, 'Emotions & Feelings', [
    WordItem('delighted', 'vui mừng'),
    WordItem('furious', 'giận dữ'),
    WordItem('anxious', 'lo lắng'),
    WordItem('relieved', 'nhẹ nhõm'),
    WordItem('embarrassed', 'xấu hổ, ngượng ngùng'),
    WordItem('jealous', 'ghen tị'),
    WordItem('proud', 'tự hào'),
    WordItem('disappointed', 'thất vọng'),
    WordItem('overwhelmed', 'choáng ngợp, quá tải'),
    WordItem('grateful', 'biết ơn'),
    WordItem('nervous', 'hồi hộp, lo lắng'),
    WordItem('confident', 'tự tin'),
    WordItem('guilty', 'cảm thấy có lỗi'),
    WordItem('lonely', 'cô đơn'),
    WordItem('content (feeling)', 'hài lòng, mãn nguyện'),
    WordItem('frustrated', 'bực bội, thất vọng'),
    WordItem('curious', 'tò mò'),
    WordItem('sympathetic', 'đồng cảm'),
    WordItem('bored', 'chán'),
    WordItem('excited', 'phấn khích'),
    WordItem('upset', 'buồn bực'),
    WordItem('calm', 'bình tĩnh'),
    WordItem('hopeful', 'đầy hy vọng'),
    WordItem('miserable', 'khổ sở, đau khổ'),
    WordItem('touched (emotionally)', 'xúc động'),
  ]),
  LevelInfo(17, 'Personality Adjectives', [
    WordItem('honest', 'trung thực'),
    WordItem('stubborn', 'cứng đầu, bướng bỉnh'),
    WordItem('generous', 'hào phóng'),
    WordItem('selfish', 'ích kỷ'),
    WordItem('outgoing', 'hướng ngoại, cởi mở'),
    WordItem('reserved', 'kín đáo, ít nói'),
    WordItem('ambitious', 'có hoài bão, tham vọng'),
    WordItem('reliable', 'đáng tin cậy'),
    WordItem('careless', 'bất cẩn'),
    WordItem('humble', 'khiêm tốn'),
    WordItem('arrogant', 'kiêu ngạo'),
    WordItem('patient', 'kiên nhẫn'),
    WordItem('impatient', 'thiếu kiên nhẫn'),
    WordItem('cheerful', 'vui vẻ'),
    WordItem('sensitive', 'nhạy cảm'),
    WordItem('confident', 'tự tin'),
    WordItem('shy', 'nhút nhát'),
    WordItem('optimistic', 'lạc quan'),
    WordItem('pessimistic', 'bi quan'),
    WordItem('creative', 'sáng tạo'),
    WordItem('adventurous', 'thích phiêu lưu'),
    WordItem('cautious', 'thận trọng'),
    WordItem('determined', 'quyết tâm'),
    WordItem('easy-going', 'dễ tính'),
    WordItem('thoughtful', 'chu đáo, sâu sắc'),
  ]),
  LevelInfo(18, 'Time Expressions', [
    WordItem('nowadays', 'ngày nay'),
    WordItem('eventually', 'cuối cùng, rốt cuộc'),
    WordItem('occasionally', 'thỉnh thoảng'),
    WordItem('frequently', 'thường xuyên'),
    WordItem('recently', 'gần đây'),
    WordItem('beforehand', 'trước đó, từ trước'),
    WordItem('meanwhile', 'trong khi đó'),
    WordItem('immediately', 'ngay lập tức'),
    WordItem('gradually', 'dần dần'),
    WordItem('simultaneously', 'đồng thời'),
    WordItem('previously', 'trước đây'),
    WordItem('shortly', 'chẳng bao lâu nữa'),
    WordItem('temporarily', 'tạm thời'),
    WordItem('permanently', 'vĩnh viễn'),
    WordItem('eventually', 'cuối cùng'),
    WordItem('punctually', 'một cách đúng giờ, chuẩn giờ'),
    WordItem('ahead of time', 'trước thời hạn'),
    WordItem('on time', 'đúng giờ'),
    WordItem('overdue', 'quá hạn'),
    WordItem('in advance', 'trước, từ trước'),
    WordItem('nowadays', 'hiện nay'),
    WordItem('henceforth', 'từ nay trở đi'),
    WordItem('periodically', 'định kỳ'),
    WordItem('upcoming', 'sắp tới'),
    WordItem('timeless', 'vượt thời gian, mãi mãi'),
  ]),
  LevelInfo(19, 'Directions & Places in Town', [
    WordItem('intersection', 'giao lộ'),
    WordItem('roundabout', 'vòng xuyến giao thông'),
    WordItem('pedestrian', 'người đi bộ'),
    WordItem('crosswalk', 'vạch qua đường'),
    WordItem('landmark', 'địa danh nổi bật'),
    WordItem('suburb', 'ngoại ô'),
    WordItem('downtown', 'trung tâm thành phố'),
    WordItem('alley', 'con hẻm'),
    WordItem('pavement', 'vỉa hè'),
    WordItem('signpost', 'biển chỉ đường'),
    WordItem('straight ahead', 'đi thẳng'),
    WordItem('turn left', 'rẽ trái'),
    WordItem('turn right', 'rẽ phải'),
    WordItem('nearby', 'gần đó'),
    WordItem('opposite', 'đối diện'),
    WordItem('block (street)', 'dãy nhà/khối phố'),
    WordItem('route', 'tuyến đường'),
    WordItem('junction', 'ngã tư/giao lộ'),
    WordItem('pedestrian crossing', 'vạch qua đường cho người đi bộ'),
    WordItem('outskirts', 'vùng ven, ngoại thành'),
    WordItem('municipality', 'chính quyền địa phương/thành phố'),
    WordItem('congested', 'tắc nghẽn (giao thông)'),
    WordItem('commute', 'đi lại (đi làm hàng ngày)'),
    WordItem('detour', 'đường vòng, đường tránh'),
    WordItem('vicinity', 'khu vực lân cận'),
  ]),
  LevelInfo(20, 'Animals', [
    WordItem('mammal', 'động vật có vú'),
    WordItem('predator', 'động vật săn mồi'),
    WordItem('prey', 'con mồi'),
    WordItem('species', 'loài'),
    WordItem('habitat', 'môi trường sống'),
    WordItem('breed (animals)', 'nhân giống, sinh sản'),
    WordItem('herd', 'đàn (gia súc)'),
    WordItem('flock', 'đàn (chim/cừu)'),
    WordItem('carnivore', 'động vật ăn thịt'),
    WordItem('herbivore', 'động vật ăn cỏ'),
    WordItem('nocturnal', 'hoạt động về đêm'),
    WordItem('migrate', 'di cư'),
    WordItem('extinct', 'tuyệt chủng'),
    WordItem('offspring', 'con non'),
    WordItem('tame', 'thuần hóa, thuần tính'),
    WordItem('wild', 'hoang dã'),
    WordItem('venomous', 'có nọc độc'),
    WordItem('camouflage', 'ngụy trang'),
    WordItem('hibernate', 'ngủ đông'),
    WordItem('livestock', 'gia súc'),
    WordItem('fur', 'lông (thú)'),
    WordItem('claw', 'móng vuốt'),
    WordItem('shell', 'vỏ (rùa, sò...)'),
    WordItem('den', 'hang (thú)'),
    WordItem('mate (animal)', 'giao phối, kết đôi'),
  ]),
  LevelInfo(21, 'Phrasal Verbs', [
    WordItem('give up', 'từ bỏ'),
    WordItem('look after', 'chăm sóc'),
    WordItem('carry on', 'tiếp tục'),
    WordItem('figure out', 'tìm ra, hiểu ra'),
    WordItem('put off', 'trì hoãn'),
    WordItem('run out of', 'hết (cái gì đó)'),
    WordItem('take off (plane)', 'cất cánh'),
    WordItem('turn down', 'từ chối'),
    WordItem('bring up (topic)', 'đề cập tới'),
    WordItem('get over', 'vượt qua (khó khăn/bệnh)'),
    WordItem('come across', 'tình cờ gặp/thấy'),
    WordItem('look forward to', 'mong chờ'),
    WordItem('break down', 'hỏng hóc (máy móc)'),
    WordItem('check in', 'làm thủ tục nhận phòng/lên máy bay'),
    WordItem('check out', 'làm thủ tục trả phòng'),
    WordItem('find out', 'tìm hiểu ra'),
    WordItem('hold on', 'chờ một chút'),
    WordItem('point out', 'chỉ ra'),
    WordItem('set up', 'thiết lập'),
    WordItem('show up', 'xuất hiện, đến'),
    WordItem('work out', 'tập luyện/giải quyết được'),
    WordItem('call off', 'hủy bỏ'),
    WordItem('cut down on', 'cắt giảm'),
    WordItem('keep up with', 'theo kịp'),
    WordItem('put up with', 'chịu đựng'),
  ]),
  LevelInfo(22, 'Prepositions & Connectors', [
    WordItem('although', 'mặc dù'),
    WordItem('in spite of', 'mặc dù, bất chấp'),
    WordItem('due to', 'do bởi, vì lý do'),
    WordItem('as a result', 'kết quả là'),
    WordItem('in addition', 'thêm vào đó'),
    WordItem('on the other hand', 'mặt khác'),
    WordItem('furthermore', 'hơn nữa'),
    WordItem('nevertheless', 'tuy nhiên, dù vậy'),
    WordItem('therefore', 'vì vậy'),
    WordItem('besides', 'bên cạnh đó'),
    WordItem('unless', 'trừ khi'),
    WordItem('provided that', 'với điều kiện là'),
    WordItem('whereas', 'trong khi (đối lập)'),
    WordItem('consequently', 'do đó, hệ quả là'),
    WordItem('similarly', 'tương tự'),
    WordItem('in contrast', 'ngược lại'),
    WordItem('apart from', 'ngoài ra, ngoại trừ'),
    WordItem('according to', 'theo như'),
    WordItem('regarding', 'liên quan đến'),
    WordItem('throughout', 'xuyên suốt'),
    WordItem('despite', 'dù cho, mặc cho'),
    WordItem('in order to', 'để mà, nhằm'),
    WordItem('as long as', 'miễn là'),
    WordItem('otherwise', 'nếu không thì'),
    WordItem('moreover', 'vả lại, hơn thế nữa'),
  ]),
  LevelInfo(23, 'Synonyms (Common B1 Adjectives)', [
    WordItem('huge', 'to lớn (= big)'),
    WordItem('tiny', 'bé xíu (= small)'),
    WordItem('exhausted', 'kiệt sức (= very tired)'),
    WordItem('delighted', 'vui sướng (= very happy)'),
    WordItem('furious', 'giận dữ (= very angry)'),
    WordItem('terrified', 'sợ hãi tột độ (= very scared)'),
    WordItem('astonished', 'kinh ngạc (= very surprised)'),
    WordItem('filthy', 'rất bẩn (= very dirty)'),
    WordItem('spotless', 'sạch tinh tươm (= very clean)'),
    WordItem('ancient', 'cổ xưa (= very old)'),
    WordItem('brand-new', 'hoàn toàn mới (= very new)'),
    WordItem('gorgeous', 'tuyệt đẹp (= very beautiful)'),
    WordItem('hideous', 'xấu xí (= very ugly)'),
    WordItem('freezing', 'lạnh cóng (= very cold)'),
    WordItem('boiling', 'nóng bỏng (= very hot)'),
    WordItem('starving', 'đói lả (= very hungry)'),
    WordItem('stuffed', 'no căng (= very full)'),
    WordItem('thrilled', 'phấn khích (= very excited)'),
    WordItem('essential', 'thiết yếu (= very important)'),
    WordItem('simple', 'đơn giản (= easy)'),
    WordItem('difficult', 'khó khăn (= hard)'),
    WordItem('wealthy', 'giàu có (= rich)'),
    WordItem('impoverished', 'nghèo khó (= very poor)'),
    WordItem('bright', 'sáng sủa, thông minh (= intelligent)'),
    WordItem('dim', 'mờ, tối (= not bright)'),
  ]),
  LevelInfo(24, 'Idioms & Expressions', [
    WordItem('piece of cake', 'việc dễ như trở bàn tay'),
    WordItem('break the ice', 'phá vỡ sự ngượng ngùng ban đầu'),
    WordItem('cost an arm and a leg', 'đắt đỏ'),
    WordItem('under the weather', 'cảm thấy không khỏe'),
    WordItem('hit the books', 'học hành chăm chỉ'),
    WordItem('once in a blue moon', 'hiếm khi xảy ra'),
    WordItem('on the same page', 'cùng quan điểm, hiểu nhau'),
    WordItem('call it a day', 'dừng công việc lại (kết thúc)'),
    WordItem('let the cat out of the bag', 'làm lộ bí mật'),
    WordItem('a piece of the pie', 'một phần lợi ích/chia sẻ'),
    WordItem('hang in there', 'cố gắng chịu đựng, đừng bỏ cuộc'),
    WordItem('miss the boat', 'bỏ lỡ cơ hội'),
    WordItem('get the ball rolling', 'bắt đầu tiến hành việc gì đó'),
    WordItem('speak of the devil', 'nhắc Tào Tháo, Tào Tháo đến'),
    WordItem('time flies', 'thời gian trôi nhanh'),
    WordItem('break a leg', 'chúc may mắn'),
    WordItem('out of the blue', 'đột nhiên, bất ngờ'),
    WordItem('piece by piece', 'từng chút một'),
    WordItem('in the long run', 'về lâu về dài'),
    WordItem('make ends meet', 'xoay xở đủ sống'),
    WordItem('keep an eye on', 'trông chừng, để mắt tới'),
    WordItem('last but not least', 'cuối cùng nhưng không kém phần quan trọng'),
    WordItem('a blessing in disguise', 'trong cái rủi có cái may'),
    WordItem('burn the midnight oil', 'thức khuya làm việc/học bài'),
    WordItem('bite the bullet', 'cắn răng chịu đựng, chấp nhận điều khó khăn'),
  ]),
  LevelInfo(25, 'Communication & Media', [
    WordItem('broadcast', 'phát sóng'),
    WordItem('headline', 'tiêu đề tin tức'),
    WordItem('journalist', 'nhà báo'),
    WordItem('interview', 'phỏng vấn'),
    WordItem('advertisement', 'quảng cáo'),
    WordItem('subscribe', 'đăng ký theo dõi/nhận'),
    WordItem('audience', 'khán giả, người xem/nghe'),
    WordItem('publish', 'xuất bản, đăng tải'),
    WordItem('rumor', 'tin đồn'),
    WordItem('gossip', 'chuyện phiếm, ngồi lê đôi mách'),
    WordItem('negotiate', 'đàm phán'),
    WordItem('persuade', 'thuyết phục'),
    WordItem('announce', 'thông báo'),
    WordItem('caption', 'chú thích (ảnh/video)'),
    WordItem('censorship', 'sự kiểm duyệt'),
    WordItem('influence', 'ảnh hưởng'),
    WordItem('misleading', 'gây hiểu lầm'),
    WordItem('reliable (source)', 'đáng tin cậy'),
    WordItem('column (newspaper)', 'chuyên mục (báo)'),
    WordItem('editor', 'biên tập viên'),
    WordItem('livestream', 'phát trực tiếp'),
    WordItem('viral (online)', 'lan truyền nhanh (trên mạng)'),
    WordItem('comment', 'bình luận'),
    WordItem('update (news)', 'tin cập nhật'),
    WordItem('headline news', 'tin tức hàng đầu'),
  ]),
];